---

resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"
output_files: "config/output_files.yaml"

modules:
  alignment: "v0.4.0"
  annotation: "v0.3.0"
  cnv_sv: "78f270c"
  prealignment: "v1.0.0"
  snv_indels: "v0.3.0"
  qc: "ca947b1"

default_container: "docker://hydragenetics/common:0.1.9"

reference:
  fasta: ""
  fai: ""
  sites: ""
  design_bed: "reference/design.bed"
  design_intervals: ""
  exon_bed: ""
  exon_intervals: ""
  skip_chrs:
    - "chr4"
    - "chr6"
    - "chr14"
    - "chr15"
    - "chr20"
    - "chr21"
    - "chrX"
    - "chrY"
    - "chrM"


trimmer_software: fastp_pe

bwa_mem:
  container: "docker://hydragenetics/bwa_mem:0.7.17"
  amb: ""
  ann: ""
  bwt: ""
  pac: ""
  sa: ""

fastp_pe:
  container: "docker://hydragenetics/fastp:0.20.1"

fastqc:
  container: "docker://hydragenetics/fastqc:0.11.9"

haplotypecaller:
  container: "docker://hydragenetics/gatk4:4.2.2.0"
  extra: ""

exomedepth_call:
  container: "docker://hydragenetics/exomedepth:1.1.15"
  bedfile: ""
  ref_count: ""
  genome_version: "hg38"
  genesfile: ""
  exonsfile: ""

mosdepth_bed:
  container: "docker://hydragenetics/mosdepth:0.3.2"
  thresholds: "10,20,50"

multiqc:
  container: "docker://hydragenetics/multiqc:1.11"
  reports:
    DNA:
      included_unit_types: ['T', 'N']
      config: "config/multiqc_config.yaml"
      qc_files:
        - "prealignment/fastp_pe/{sample}_{type}_{flowcell}_{lane}_{barcode}_fastp.json"
        - "qc/fastqc/{sample}_{type}_{flowcell}_{lane}_{barcode}_{read}_fastqc.zip"
        - "qc/picard_collect_alignment_summary_metrics/{sample}_{type}.alignment_summary_metrics.txt"
        - "qc/picard_collect_duplication_metrics/{sample}_{type}.duplication_metrics.txt"
        - "qc/picard_collect_gc_bias_metrics/{sample}_{type}.gc_bias.summary_metrics"
        - "qc/picard_collect_hs_metrics/{sample}_{type}.HsMetrics.txt"
        - "qc/picard_collect_insert_size_metrics/{sample}_{type}.insert_size_metrics.txt"
        - "qc/picard_collect_multiple_metrics/{sample}_{type}.{ext}"
        - "qc/samtools_stats/{sample}_{type}.samtools-stats.txt"
        - "qc/mosdepth_bed/{sample}_{type}.mosdepth.summary.txt"
        - "qc/mosdepth_bed/{sample}_{type}.per-base.bed.gz"
        - "qc/mosdepth_bed/{sample}_{type}.mosdepth.region.dist.txt"
        - "qc/mosdepth_bed/{sample}_{type}.mosdepth.global.dist.txt"

picard_collect_alignment_summary_metrics:
  container: "docker://hydragenetics/picard:2.25.4"

picard_collect_duplication_metrics:
  container: "docker://hydragenetics/picard:2.25.4"

picard_collect_gc_bias_metrics:
  container: "docker://hydragenetics/picard:2.25.4"
  
picard_collect_hs_metrics:
  container: "docker://hydragenetics/picard:2.25.4"

picard_collect_insert_size_metrics:
  container: "docker://hydragenetics/picard:2.25.4"

picard_collect_multiple_metrics:
  container: "docker://hydragenetics/picard:2.25.4"
  output_ext:
    - "gc_bias.pdf" #collect_gc_bias
    - "gc_bias.summary_metrics"
    - "gc_bias.detail_metrics"
    - "alignment_summary_metrics" # collect_alignment_summary
    - "insert_size_metrics" # collect_insert_size
    - "insert_size_histogram.pdf"
    - "error_summary_metrics" # collect_sequencing_artefact
    - "bait_bias_detail_metrics"
    - "bait_bias_summary_metrics"
    - "pre_adapter_detail_metrics"
    - "pre_adapter_summary_metrics"
    - "quality_distribution_metrics" # quality_score_distribution
    - "quality_distribution.pdf"
    - "quality_yield_metrics" # quality yield metrics

picard_mark_duplicates:
  container: "docker://hydragenetics/picard:2.25.4"

sample_order_multiqc:
  sample_sheet: "SampleSheet.csv"

vep:
  container: "docker://hydragenetics/vep:109"
  vep_cache: "reference/vep_cache"
  extra: "--assembly GRCh38 --check_existing --pick --sift b --polyphen b --ccds --uniprot --hgvs --symbol --numbers --domains --regulatory --canonical --protein --biotype --uniprot --tsl --appris --gene_phenotype --af --af_1kg --af_gnomad --max_af --pubmed --variant_class "

vt_decompose:
  container: "docker://hydragenetics/vt:2015.11.10"

vt_normalize:
  container: "docker://hydragenetics/vt:2015.11.10"

