samples: "samples.tsv"
units:  "units_references.tsv"
resources: "resources.yaml"

default_container: "docker://hydragenetics/common:1.8.1"

reference:
  design_bed: "/projects/wp3/nobackup/TwistCancer/Bedfiles/Twist_Cancer_230706_hg38_TE-98982205-wPGRS.merged_200bpwindows.bed"

exomedepth_reference:
  container: "docker://hydragenetics/exomedepth:1.1.15"
