directory: ./Results
files:
  - name: MultiQC
    input: qc/multiqc/multiqc_DNA.html
    output: "{sequenceid}_MultiQC.html"
  - name: QC xlsx-report
    input: qc/xlsx_report/{sample}_N.xlsx
    output: "{sample}_{sequenceid}/{sample}_{sequenceid}.xlsx"
  - name: Alignment bam file
    input: alignment/samtools_merge_bam/{sample}_N.bam
    output: "{sample}_{sequenceid}/{sample}_{sequenceid}.bam"
  - name: Alignment bai file
    input: alignment/samtools_merge_bam/{sample}_N.bam.bai
    output: "{sample}_{sequenceid}/{sample}_{sequenceid}.bam.bai"
  - name: Annotated vcf file
    input: parabricks/pbrun_deepvariant/{sample}_N.normalized.sorted.vep_annotated.ref.vcf.gz
    output: "{sample}_{sequenceid}/{sample}_{sequenceid}.vcf.gz"
  - name: Annotated vcf tbi file
    input: parabricks/pbrun_deepvariant/{sample}_N.normalized.sorted.vep_annotated.ref.vcf.gz.tbi
    output: "{sample}_{sequenceid}/{sample}_{sequenceid}.vcf.gz.tbi"
  - name: Genome vcf file no normalize
    input: parabricks/pbrun_deepvariant/{sample}_N.g.fix_af.vcf.gz
    output: "{sample}_{sequenceid}/{sample}_{sequenceid}.genome.vcf.gz"
  - name: Genome vcf index file no normalize
    input: parabricks/pbrun_deepvariant/{sample}_N.g.fix_af.vcf.gz.tbi
    output: "{sample}_{sequenceid}/{sample}_{sequenceid}.genome.vcf.gz.tbi"
  - name: Exomedepth nexus
    input: cnv_sv/exomedepth_call/{sample}_N_SV.txt
    output: "{sample}_{sequenceid}/{sample}_{sequenceid}_exomedepth_SV.txt"
  - name: Exomedepth aed
    input: cnv_sv/exomedepth_call/{sample}_N.aed
    output: "{sample}_{sequenceid}/{sample}_{sequenceid}_exomedepth.aed"
  - name: Config-file
    input: config.yaml
    output: "{sequenceid}_config.yaml"
  - name: melt alu fil
    input: "cnv_sv/melt/Results_single_{sample}_{type}/ALU.final_comp.vcf"
    output: "(sample}_{sequenceid}/{sample}_{sequenceid}_melt_ALU.aed"
  - name: melt line1 fil
    input: "cnv_sv/melt/Results_single_{sample}_{type}/LINE1.final_comp.vcf"
    output: "(sample}_{sequenceid}/{sample}_{sequenceid}_melt_LINE1.aed"
  - name: melt sva fil
    input: "cnv_sv/melt/Results_single_{sample}_{type}/SVA_final_comp.vcf"
    output: "(sample}_{sequenceid}/{sample}_{sequenceid}_melt_SVA.aed"

